version: 2.1

#You can use orbs here if you wish
# orbs:
#   node: circleci/node@5.1.0

jobs:
  build_and_push:
    docker:
      - image: cimg/node:20.3.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push image
          command: |
            version="build-$CIRCLE_BUILD_NUM"
            echo $version
            docker build -t savytech/bank-app:$version .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push savytech/bank-app:$version

  Update_manifest:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Updating Manifest file 
          command: |
            TAG=$CIRCLE_BUILD_NUM
            ((TAG--))
            git clone https://github.com/lateef-taiwo/Bank-App-Kube-Manifest.git
            git config --global user.email "taiwolateef55@gmail.com"
            git config --global user.name "lateef-taiwo"
            pwd
            cd Bank-App-Kube-Manifest
            pwd
            echo $TAG
    #sed -i "s/build-.*/build-$TAG/g" manifest/deployment.yml
            cat manifest/deployment.yml
            git add .
            git commit -m "new build with imgTag build-$TAG"
            git config credential.helper 'cache --timeout=120'
            git push -q https://$GITHUB_PERSONAL_TOKEN@github.com/lateef-taiwo/Bank-App-Kube-Manifest.git main 
workflows:
  GitOpsflow:
    jobs:
      - build_and_push
      - Update_manifest:
          requires:
            - build_and_push

#Add more workflows.
